project:
  output-dir: ../docs

author:
  - name: Nicki Baumgart
    email: baumgartae@vcu.edu
  - name: Lorelai Davis
    email: davisla10@vcu.edu

format:
  html:
    toc: true
    embed-resources: true
    html-math-method: katex
    theme: cosmo
